language: node_js
script: npm run release
node_js: node
deploy:
  provider: npm
  email: hyjiacan@163.com
  api_key:
    secure: IjUaOIGdLfIeWyndalcuxB2NcjwiGv6i423oQlOYeD/cxdcYoYSRYSyAdCxn6UgqgnYHotSFdemHrDiLfwrftVfeH8Nz+4EoZWBSG5EEefzq35kc1hMrABU2vPfmdSjB/2aLcu7Z5694kL6eWzs2xox5n+Ttrih63N2vzvlaEJE+gkIF+Wqwr/t1HKVWKjfdm5i/Xh15nq17mXB59KM0500LnFsU/0ubjILfHUYeIK5i7Sc/LuKRHxEgPiQ/qE/cZLJaQhBv7HetrnbEi9JxWVfyWHCVLSRYoVfTRjzTsz+OFXGcYV9PwsVjiIugIw3GR3dy+7lEmQf/uo3xXVRE5JyJpGSxiRMKVNzjXhDSwLvORwEhjS0L4+1iuLNbkKdooEQevbgzoBpHvdrqP7SyQEFlWUuwsNTHuGogY1JJ6t3SLxR3SAaooa0/r0s+Mc5ZOPWRqyqyg8W3VB/xJRa4Gy8UJYDhf0qpzf4qIxYKTkir50YuoFTKSxhbtXFwNWIYluQuOTXICcsXQEsDdFfd9LQqDRtRZBMybFAVxfZtklfmH/Ec+26Mb00Cynoucl59vZVjB+nEhHzgnESzLIahllJP3ms1bPiWb+HFosuAttFdirfWqRsZNdBSjTOCnB952ZJbATrU7GJE2VhscxiSndwc8ZH8bleMNQXXYAr+b7g=
  on:
    tags: true
    repo: hyjiacan/vue-slideout
